name: phpstan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nxtlvlsoftware/pmmp-phpstan-action@stable
      with:
        source: EffectEventTesting
